"""modified departments table name

Revision ID: f42982e1cd3a
Revises: 4122401c5a64
Create Date: 2023-11-13 10:10:40.039754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f42982e1cd3a'
down_revision = '4122401c5a64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.rename_table('departments', 'department')
    # ### end Alembic commands ###
